LINE_PLOT = 'line-plot'
INTERVAL_COMPONENT = 'interval-component'
TEAM_DROPDOWN = 'team-dropdown'
PIE_CHART = 'pie-chart'
LINE_PLOT_COMMENT_COUNT = 'line-plot-comment_count'
TIME_WINDOW_BUTTONS = 'time-window-buttons'
PLOT_TYPE_BUTTONS = 'plot-type-buttons'